version: 0.2

phases:
 
  build:
    commands:
      - echo Enter the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on successfully
artifacts:
  files:
    - target/RESTAPIDEMO.jar
  discard-paths: yes